/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    CellDisplay: typeof import('./src/components/CellDisplay.vue')['default']
    CellEditor: typeof import('./src/components/CellEditor.vue')['default']
    CellRenderer: typeof import('./src/components/CellRenderer.vue')['default']
    FieldManagerModal: typeof import('./src/components/modals/FieldManagerModal.vue')['default']
    FilterGroup: typeof import('./src/components/modals/FilterGroup.vue')['default']
    FilterModal: typeof import('./src/components/modals/FilterModal.vue')['default']
    FormField: typeof import('./src/components/FormField.vue')['default']
    FormGeneratorModal: typeof import('./src/components/modals/FormGeneratorModal.vue')['default']
    GroupModal: typeof import('./src/components/modals/GroupModal.vue')['default']
    PerformanceMonitor: typeof import('./src/components/PerformanceMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareContainer: typeof import('./src/components/ShareContainer.vue')['default']
    TableContainer: typeof import('./src/components/TableContainer.vue')['default']
    TableToolbar: typeof import('./src/components/TableToolbar.vue')['default']
    ViewTabs: typeof import('./src/components/ViewTabs.vue')['default']
    VirtualRow: typeof import('./src/components/VirtualRow.vue')['default']
    VirtualTable: typeof import('./src/components/VirtualTable.vue')['default']
  }
}
